### ISSUE TITLE
Read the Docs

### ISSUE THREAD

**Issue by itdependsnetworks** [PaloAltoNetworks/pan-os-ansible#23]
## Documentation link

https://ansible-pan.readthedocs.io/en/latest/

## Describe the problem

Seems that the readthedocs is pointing to old repo.

## Suggested fix

If this is the go-forward strategy, should be moved to here, and deprecate the ansible-pan repo

**Comment by shinmog** [comment]
Docs are weird right now.

Ansible is working towards pulling documentation from collections and publishing it so that individual contributors don't have to maintain their own docs, but it's not quite done yet.  Then there's us, we have docs for the old repo up, but I don't want to setup new docs because that will be throw away work once Ansible does the Galaxy auto docs.  So I've just temporarily done this half in half out documentation thing for this collection, where I mention it in the role's docs, but there's no role-specific HTML docs (you can always use `ansible-doc` to get module documentation).

Hopefully it won't be too much longer until they fix this on their end, then I can safely retire the old role and docs page.

I'll leave this open until Ansible is auto-generating collection docs, because there may be something I need to do on my end to facilitate it further.

**Comment by stealthllama** [comment]
We just received an update today from Red Hat on their new approach to documentation parsing and presentation for Ansible collections.  

- Community collections in Galaxy will be automatically parsed and presented on [https://docs.ansible.com](https://docs.ansible.com).  

- Certified content collections will be parsed and presented on the [Ansible Automation Hub](https://www.ansible.com/products/automation-hub).  

They are finalizing the community parser now and should have things ironed out soon.  Once that is tested we will look to retire the RTD docs and archive the old repo.  We'll leave this issue open until that occurs.

**Comment by mrichardson03** [comment]
Docs are temporarily published at: https://paloaltonetworks.github.io/pan-os-ansible/ while this gets sorted out.
