### ISSUE TITLE
Adjust collection requirements

### ISSUE THREAD

**Issue by ryanmerolle** [PaloAltoNetworks/pan-os-ansible#307]
### Is your feature request related to a problem?

This collection makes it hard to build ansible execution environments given the strict pinning of requirements.txt packages.  When ansible-builder attempts to build an execution environment with this collection and other collections that overlap with requirements like with the requests package, the build fails.

### Describe the solution you'd like

Allow ranges of packages in requirements.txt using `>=` and `<=` where possible.

### Describe alternatives you've considered

Build execution environments just for palo alto, but that means I cannot create playbooks that leverage collections besides palo alto in a playbook that uses said collection.

### Additional context

This collection could use an update regardless in terms of leveraged packages.

**Comment by damluji** [comment]
yes, this is a problem for us as well.. right now i keep running into a problem trying to upgrade the pan-os-python version:

` ERROR: Could not find a version that satisfies the requirement pan-os-python==1.5.1,==1.7.1
## this is due to:
 #17 0.306 - 'pan-os-python==1.5.1,==1.7.1  # from collection paloaltonetworks.panos,user'
`

**Comment by 2ps** [comment]
@damluji , @ryanmerolle -- do you mean this as contributors to the collection or do you mean this as users of this collection's capabilities in roles and playbooks?

**Comment by damluji** [comment]
hi, for me, its as a user of the collection. it blocks us from upgrading as it requires `==1.7.1` :(

**Comment by RussTech** [comment]
In my case, I'm using ansible-builder to install and configure a longer list of collections.  Today i bumped into this: 

The conflict is caused by:
  The user requested requests==2.22.0 and >=2.4.2
  azure-cli-core 2.26.1 depends on requests~=2.25.1

If I exclude that collection from the ansible-builder and install it at execution time then everything does work.  so the requests==2.22.0 does not need to be that strict
