### ISSUE TITLE
panos_software .py - is_valid_sequence should be run only if install is set to True

### ISSUE THREAD

**Issue by thomaschristory** [PaloAltoNetworks/pan-os-ansible#454]
## Describe the bug

I am trying to download 2 major release on my firewalls in order to prepare for a big upgrade (9.1 to 10.1).
I am using the download only module.

## Expected behavior

I expect to be able to pre-load any firmware I want on the firewall as long as I don't install anything.

## Current behavior

Instead, I get "Version Sequence is invalid: 9.1.14-h4 -> 10.1.0".

## Possible solution

the is_valid_sequence should be called in the if install = True sequence and not at the top (after line 256).

## Steps to reproduce

Using the download_panos_version.yml playbook and trying to get a version that is two major release away from the current version (like 10.1 from 9.1)

## Screenshots

n/a

## Context

We're trying to update 1200+ physical firewalls, with crappy b/w and no downtime, so being able to pre-load the images is mandatory

## Your Environment

Panorama / Pa220 / Pa820 / Pa440
latest ansible collection

**Comment by jamesholland-uk** [comment]
Hi @thomaschristory, I believe the module is blocking an invalid upgrade path for a direct installation (9.1.x direct to 10.1.x is not valid). However, because you are only downloading PAN-OS images, the download should be valid if you are not doing the install of 9.1.x -> 10.1.x, but just downloading images for a two-step upgrade later on? If so, the module needs to be more lenient with download-only usage and not check the install path is valid?

Can you confirm my understanding of your use case is correct? Thanks!

**Comment by thomaschristory** [comment]
Hello James,

This is correct, that's how I was expecting it to work :)

Thanks,

Thomas

**Comment by thomaschristory** [comment]
thanks for the fix :)
