### ISSUE TITLE
Can't find ansible_network_os and connection that should be used. 

### ISSUE THREAD

**Issue by jdelaporte** [PaloAltoNetworks/pan-os-ansible#73]
## Documentation link

I haven't found the documentation I need. 

## Describe the problem

Request for improvement.
When I use the collection to connect to a PANOS device, I get the error: "network os panos is not supported" from panos_facts module.

vars
connection: network-cli
ansible_network_os: panos

I have tried connection: ssh, which resulted in bigger problems as expected.
It is not clear what `connection` and `ansible_network_os` should be used.

**Comment by stealthllama** [comment]
Hi @jdelaporte,

The connection type should be `local` since we're using API connections from the [pan-os-python](https://github.com/PaloAltoNetworks/pan-os-python) (formerly `pandevice`) connection helper.

We're considering a move to the `httpapi` connection method down the road, but for now it is `local` and `ansible_network_os` is not needed.

Hope this helps!

**Comment by jdelaporte** [comment]
That's great! Thank you. I'll try to set up a PR this week to add to
documentation.

Joanna

**Comment by mrichardson03** [comment]
We have added an example playbook repository at https://github.com/PaloAltoNetworks/ansible-playbooks you can reference.
